# -*- coding: utf-8 -*-
"""Hidden_Markov_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E700VZCsB6MkkuTvkChL4uCJgAaHwueh
"""

!pip install hmmlearn

from sklearn import datasets
from hmmlearn import hmm
import numpy as np

# Loading Iris dataset
iris = datasets.load_iris()
X = iris.data

# Training the HMM model
model = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100)
model.fit(X)

# Generating a sequence of observations from the model
generated_samples, _ = model.sample(5)

print("Generated Samples:")
print(generated_samples)